services:

    twig.extension.becklyn.bootstrap:
        class: Becklyn\BootstrapBundle\Service\TwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
